// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://spxfgsguqcmcblsqznbv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNweGZnc2d1cWNtY2Jsc3F6bmJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMDQ5OTMsImV4cCI6MjA3Mjg4MDk5M30.iQm4FhAby9EJ1peMvDfj65CGeWixC3hmOhFkWorB3Tw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});