// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gluffcyjkrfrqvogljmf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdsdWZmY3lqa3JmcnF2b2dsam1mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MjkwMDcsImV4cCI6MjA3MDQwNTAwN30.1p5ZxEEmwHOoc5WCL6uMK3ePWaVXwnZtWXIKMw270CA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});